server:
  port: 18091

spring:
  influxdb:
    url: http://localhost:8086
    username: root
    password: root
    database: test
    retention-policy: autogen
    connect-timeout: 10
    read-timeout: 30
    write-timeout: 10